version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - apk add --update npm
  build:
    commands:
      - npm install 
      - npm run lint
      - npm run build
artifacts:
  files:
    - '**/*'
